### ISSUE TITLE
Haxe 4.2.3: Doesnt work

### ISSUE THREAD

**Issue by CrazyFlasher** [haxe-utest/utest#111]
Haxe: 4.2.3
```haxe
class TestMain
{
    public static function main()
    {
        var runner:Runner = new Runner();
        // runner.addCases("com.domwires.ext");
        runner.addCase(TemplateTest);

        Report.create(runner);
        runner.run();
    }
}

import utest.Assert;
import utest.Test;

class TemplateTest extends Test
{
    public function testTemplateTest():Void
    {
        Assert.isTrue(true);
    }
}
```
```
-main TestMain
-lib hexinject
-lib hxnodejs
-lib DomWires
-lib utest
-cp src
-cp test
-js build/test.js
-D utest
-cmd node build/test.js --inspect
```
Error
```
C:\work\projects\domwires-ext-hx\build\test.js:304
        for(var i in c.prototype) a.push(i);
                       ^

TypeError: Cannot read property 'prototype' of null
    at Function.Type.getInstanceFields (C:\work\projects\domwires-ext-hx\build\test.js:304:17)
    at utest_Runner.addCaseOld (C:\work\projects\domwires-ext-hx\build\test.js:2555:21)
    at utest_Runner.addCase (C:\work\projects\domwires-ext-hx\build\test.js:2495:9)
    at Function.TestMain.main (C:\work\projects\domwires-ext-hx\build\test.js:278:9)
    at C:\work\projects\domwires-ext-hx\build\test.js:3934:10
    at Object.<anonymous> (C:\work\projects\domwires-ext-hx\build\test.js:3935:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Error: Command failed with error 1
```

**Comment by CrazyFlasher** [comment]
Sorry for my inattentiveness. I had to pass new instance instead of class to addCase method. May be it would be good to check this compile time?

**Comment by player-03** [comment]
The documentation says "`TestCase` must extend `utest.Test` or implement `utest.ITest`," but that isn't true, because there's still an old implementation lying around. This alternate implementation is the only reason you didn't get a proper error message. Maybe it's time to deprecate it?

**Comment by player-03** [comment]
Update: they removed the old implementation, so now it checks the type at compile time.

**Comment by RealyUniqueName** [comment]
Yes, this should not be an issue anymore.
Sorry for such a long silence.
